server:
  ## 端口
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://10.20.2.9:3306/sapweb?useUnicode=true&characterEncoding=utf8
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver